### ISSUE TITLE
Create a README file parser

### ISSUE THREAD

**Issue by dtinth** [ThaiProgrammer/tech-events-calendar#1]
This makes it possible for:

- Linting the README file (for pull requests).
    - We can use [prontolabs/pronto](https://github.com/prontolabs/pronto) to automatically add pull request reviews!
- Generate a JSON file for event data.
- Synchronize the event data to Google Calendar.
- Generating a web page.

Ideally, I would prefer that this parser is added to this repository, because the file format of README.md is subject to change, so we can update the format and the parser together, and not break integrations.

**Comment by iboss-ptk** [comment]
This sounds very clojure to me!

**Comment by dodadoa** [comment]
@iboss-ptk sounds Clojure to me too :rofl:

**Comment by dtinth** [comment]
@iboss-ptk @dodadoa Sounds great! I would say these are the baseline requirements:

- Be able to parse the README file and generate JSON file. I plan to have a CI deploy the JSON file somewhere so that other developers can read this JSON file.

- Be able to detect errors in README file and integrate with Pronto.

If you would like to work on this please let me know in the comment, to reduce duplicated efforts.

Tagging @phoomparin as he is reading Clojure for the Brave and True!!

**Comment by iboss-ptk** [comment]
I would love to :)

**Comment by iboss-ptk** [comment]
Few questions while working on it:

- `16:00~17:00++`
 Should we add space around `~` for consistency, and get rid of `++` since it will have no meaning on calendar? Then it will become like this `16:00 ~ 17:00`

- Should `Website`, `Get tickets` and `RSVP` always be link?
- Should I enforce the sequence of legends in the table? What is required/optional or can have more than one?

**Comment by dtinth** [comment]
@iboss-ptk

Yes, there should be a space around `~`.

The `++`, you can safely ignore it, because it signifies a meaning that it can go further as long as the participants wish and time allows.

Yes, 🏠, 🎟 and ✅ should always be link.

About the sequence, I think it would be nice but not required.

I would say `🏷📍⌚️*[🏠🎟✅]+`:

- 🏷 📍 are required, and there can be only one each for event.
- ⌚️ is optional. If not present it is assumed to be a full day event.
- 🏠 🎟 ✅ are optional and there can be multiple of each, but at least one of them should be present.

**Comment by dtinth** [comment]
@iboss-ptk @dodadoa

- Now, I have added @llun’s JavaScript parser to the project.

- Now deployed to Netlify at https://thaiprogrammer-tech-events-calendar.netlify.com/calendar.json, but I want to wait for it to run on our own domain, so that we’re not locked in to Netlify.

- CircleCI is added, so that every pull request gets README file validated: https://circleci.com/gh/ThaiProgrammer/tech-events-calendar

However,

- The parser isn’t integrated with Pronto yet. To do this, when there is an error, we need to figure out which line on the README file the error came from. (pegjs can do this but error message is not very friendly.)

- Also, there is no schema or documentation about the JSON file.

If you can improve this (e.g. by rewriting it in Clojure, or improving the current JS version), I would appreciate it a lot!

**Comment by llun** [comment]
Can try https://github.com/Engelberg/instaparse (got this from @visibletrap) The error message looks more friendlier than PEG.js. Syntax is very similar but in Clojure.

**Comment by iboss-ptk** [comment]
@dtinth I'm working on using clojure.spec to create parser which very declarative and will provide quite detailed information about the mistake since I'm parsing it to AST first and transform it to json later. I think should be able to detect line number if we need.

**Comment by iboss-ptk** [comment]
Seems like clojure.spec might not be a good idea for parsing string. I looked into @llun  work and that is awesome already (even though I don't like js lol). So I think I will PR my half-baked clojure solution just for reference.

**Comment by dtinth** [comment]
Ok, thanks @iboss-ptk! For reference here, the PR is #6.

Closing as we now have the JSON file.
