### ISSUE TITLE
License agreement of the source and data are missing

### ISSUE THREAD

**Issue by kindraywind** [ThaiProgrammer/tech-events-calendar#100]

**Comment by dtinth** [comment]
Thanks, you are right that the license in this project is missing.

For source code, I think, we can release it in MIT. For data, I don’t know, but how about CC0? Do you have any suggestions?

**Comment by kindraywind** [comment]
both MIT and CC0 1.0 is lgtm.

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
