### ISSUE TITLE
Make calendar clickable

### ISSUE THREAD

**Issue by dtinth** [ThaiProgrammer/tech-events-calendar#101]
- Tiles with no events are not clickable.
- Tiles with events take you to event list page, scrolling to the event on that day. Possibly highlighting the event.

**Comment by 0pdd** [comment]
@dtinth the puzzle [#118](https://github.com/ThaiProgrammer/tech-events-calendar/issues/118) is still not solved.

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
