### ISSUE TITLE
เสนอให้เพิ่มรายชื่อผู้เกี่ยวข้องในแต่ละอีเวนต์

### ISSUE THREAD

**Issue by kindraywind** [ThaiProgrammer/tech-events-calendar#103]
เพิ่มรายชื่อผู้เกี่ยวข้องในแต่ละอีเวนต์(เช่น ผู้จัดงานหลัก, วิทยากร, speakers)

โดยอาจจะเก็บ:
 - ชื่อ (primary key?)
 - Role (organizer, speaker, platinum sponsor, ...)
 - SNS (fb, twt, blog, website, whatever)
 - รายละเอียดสั้นๆ

คิดว่าการจัดเก็บรายชื่อน่าจะส่งผลดีต่อทั้งฐานข้อมูลและผู้ที่เกี่ยวข้อง และน่าจะเป็น incentive ให้ผู้ที่เกี่ยวข้องมาอัพเดทปฏิทินนี้ด้วย

ข้อเสียที่คิดได้ตอนนี้คือ:
 1. ข้อมูลจะ verbose ขึ้น และยากขึ้นในการเพิ่มอีเวนต์ใหม่(อาจจะแก้ได้ด้วย optional)
 2. ความสมัครใจ และ ความเป็นส่วนตัวของบุคคล

**Comment by dtinth** [comment]
I like this idea!

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
