### ISSUE TITLE
[Event] Stellar 101

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#104]
### Date and time
2018-03-17
09:00 ~ 17:00

### Location
https://g.co/kgs/r2CCYo

### Links
- Facebook event: https://www.facebook.com/events/407098259714174

### Event Summary
Stellar 101 : มาทำความรู้จัก Blockchain เพื่อการโอนถ่ายสินทรัพย์อย่างโปร่งใสและปลอดภัย

### Event description
 และลองสร้าง Token และ Smart Contract บน Stellar Network ด้วยตนเอง
โดย เมธัส แก้วทรายขาวและปราชญ์ ฮอมณีจาก Cochain และ ทศพร บรรเจิดกิจ (Katopz) จาก Digithun

**Comment by dtinth** [comment]
Thanks for the info, sorry I was busy with other stuff and had no time to update this project. I will add it today.
