### ISSUE TITLE
[Event] Basic angular by stop & o'leang

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#107]
### Date and time
2018-03-24
09:30 ~ 17:30

### Location
Geeky Base
https://goo.gl/maps/cZazeG3LZK22

### Links
- Facebook event: https://web.facebook.com/events/1618677464915280/

### Event summary
introduce angular และมีการทำ workshop เล็กน้อย

### Event description
ถ้ายังไงใครลงโปรแกรมกันมาก่อนเลยก็ได้ครับโดยโปรแกรมที่ต้องเตรียมมา
-node
-npm
-angular cli

**Comment by dtinth** [comment]
Thanks, it will be added today as well :)
