### ISSUE TITLE
[Event] Future Technology for Enterprise

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#108]
### Date and time
2018-03-24
12:30 ~ 16:30

### Location
https://goo.gl/maps/BeDDyNKyRaL2

### Links
- Facebook Photo: https://web.facebook.com/sansiricareers/photos/a.553502798055321.1073741828.111497848922487/1896202903785297/?type=3&permPage=1
- Google Form (Register): https://docs.google.com/forms/d/14o76rEz051rN-Vjl4n937HjfAJ8WCHahn9muh-dUkB8/viewform?edit_requested=true

### Event summary
แสนสิริจัดเต็มกับ Guru ที่จะมาแชร์ประสบการณ์สุด Exclusive ภายในงาน Future Technology for Enterprise

### Event description
▶️ Blockchain & Nodejs
▶️ Machine Learning , AI และ IoT
▶️ Property Tech Trend

ด่วน! รับจำนวนจำกัด
สนใจเข้าร่วมกดลงทะเบียนที่ลิงก์นี้
http://bit.ly/2p9z4RS

พบกันวันเสาร์ที่ 24 มีนาคม 2561
ลงทะเบียนเข้างาน 12:30 – 13:00 น.
ชั้น 17 อาคารสิริภิญโญ (ใกล้ BTS พญาไท)

โอกาสไม่คอยใคร ถ้าสนใจต้องเข้ามา
สอบถามข้อมูลเพิ่มเติม
โทร. 086-084-3926 / 080-808-0771

**Comment by dtinth** [comment]
Thanks!
