### ISSUE TITLE
✦ CALL FOR MAINTAINERS

### ISSUE THREAD

**Issue by dtinth** [ThaiProgrammer/tech-events-calendar#11]
เป้าหมายของโปรเจกต์นี้
คือผมต้องการให้ข้อมูลไม่ขึ้นอยู่กับเจ้าใดเจ้าหนึ่ง แต่ให้ Community ช่วยกันดูแล
ต่างจากระบบอีเวนต์อื่นๆ ที่พยายามทำตัวเป็นศูนย์รวมอีเวนต์​ แต่สุดท้ายก็มีอีเวนต์แค่ในระบบของตัวเอง

การจะบรรลุเป้าหมายนี้ได้
จำเป็นต้องมีคนมาช่วยดูแล (Maintain) โปรเจกต์ครับ

ซึ่งนอกจากการช่วยส่ง PR เพื่อแก้ไขปรับปรุงข้อมูล หรือโค้ดบางส่วน (ที่ Contributor ทั่วไปสามารถทำได้)
Maintainer จะสามารถทำงานในหน้าที่พวกนี้ได้ด้วย

- ช่วย Review และ Merge pull request ต่างๆ
- ช่วยปรับปรุงพัฒนา Architecture / Infrastructure ต่างๆ ให้ดีขึ้น
- ช่วยตัดสินใจเรื่องทิศทางของโปรเจกต์

(ซึ่งไม่จำเป็นต้องทำทุกหน้าที่นะครับ อยากทำอันไหนก็ทำอันน้ัน ช่วยๆ กัน)

ใครสนใจบอกได้นะครับบ จะได้แอดเข้าโปรเจกต์ :D

**Comment by boonitis** [comment]
สนใจช่วยครับ พอดีชอบติดตามพวก tech event อยู่พอดีครับ

**Comment by dtinth** [comment]
@boonitis That’s great!! Before I add you as a collaborator, can you fix your PR #19 as requested?

**Comment by mahasak** [comment]
@dtinth I would like to help krub, i can commit my workload at 3-4 hrs per weeks if you okay with that.

**Comment by dtinth** [comment]
@mahasak Thanks, much appreciated! No need to make any commitment though (I don’t either) as these are all voluntary work ;).

**Comment by dtinth** [comment]
@boonitis Added as collaborator — thanks!!

**Comment by matchifang** [comment]
I'd like to help out. Could you please add me as collaborator? :)

**Comment by dtinth** [comment]
@matchifang Thanks for your interest!

I have invited you to become a collaborator on this project. Please find the invitation at https://github.com/ThaiProgrammer/tech-events-calendar/invitations.

Please check out the [contributing guide](https://github.com/ThaiProgrammer/tech-events-calendar/blob/master/CONTRIBUTING.md). If you see anything that can be improved, please feel free to create a pull request.

**Comment by unnawut** [comment]
@dtinth Looks like the issues and PRs could be cleaned up a bit. Would like to be a contributor this time. :D

**Comment by dtinth** [comment]
@unnawut Thanks! An invite is on your way. Actually I plan on adopting something like [Moya Community Continuity Guidelines](https://github.com/Moya/contributors) which basically means anyone who gets a PR merged becomes a collaborator. :)

**Comment by dtinth** [comment]
I am updating the policy about contributing to this project, following [Moya Community Continuity Guidelines v2.0.0](https://github.com/Moya/contributors/blob/master/Contributing.md) — anyone who have a PR merged will receive collaborator invite to this repository. They will be able to:

- Help review and merge PRs created by other contributors.
- Submit a PR and merge themselves if the tests pass.
- Improve and evolve the project to make it better.

All of these are things you can do at your convenience, when you have time and feel like doing it. I want contributing to open-source to be fun and frictionless, not a burden.

**This applies retroactively.** I have just sent invites to the following people who have previously contributed to the project but are not on the collaborator list yet: 

@happyudong555, @lolevsky, @tonmanna, @Nann, @suksit, @mikkipastel, @chonla, @hexadi, @nichanank, @n3mz77, @TonPC64, @komcal, @Scoombe, @nual, @notjiam, @nearonline, @koobitor

You can find your invitation here:
https://github.com/ThaiProgrammer/tech-events-calendar/invitations

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
