### ISSUE TITLE
[Event] ผลักดันโครงการ National Digital ID

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#111]
### Date and time
2018-03-29
18:00 ~ 21:00

### Location
Rabbit Hub Co working space
https://goo.gl/maps/tvkA8k4nGAS2

### Links
- Facebook: https://web.facebook.com/bhume/posts/10215786550238622

### Event summary
เรียนเพื่อน ๆ ทุกท่านที่สนใจมาช่วยเหลือผลักดันโครงการ National Digital ID.

### Event description
เรียนเพื่อนๆทุกท่านที่สนใจมาช่วยเหลือผลักดันโครงการ National Digital ID. พรุ่งนี้เย็น 29 มีนาคม เวลา 18:00 ผมจะขอเชิญคนที่มาได้ มาร่วมกันระดมแรงและสมอง คุยกันถึงแผนการพัฒนาระบบนี้นะครับ รบกวน programmer developer system op, engineer, etc... scrum master, และอื่นๆ ที่สนใจ มาช่วยกัน มาร่วมมือกันได้ อยากได้ทั้ง volunteer และถ้าใครอยากได้งานทำ parttime fulltime มาร่วมประชุมกันก่อน ผมจะเล่าให้ฟังถึง detail design (สองเดือนก่อนพูด high level design ไปแล้ว) และเริ่มพัฒนาโค้ดกันเลย ทุกวัย เป็นเวลาหลายเดือน

สถานที่คือ Rabbit Hub Co working space แถวๆ BTS พญาไท ห้องXL ชั้น 1 เริ่มเวลา 18:00-21:00 วันพรุ่งนี้นะครับ และจะมีนัดต่อๆไปแน่นอน เย็นๆและเสาร์อาทิตย์ เพื่อหาคนมาช่วยเพิ่มเติม

ใครสนใจแจ้งด่วน ใครรู้จักคนที่สนใจใช้ความรู้ IT, Dev เพื่อชาติ (แต่ถ้าอยากได้ค่าจ้างก็อาจจะมีให้นะ ไม่ต้องฟรีแบบผม) มาด่วนๆ

update: https://web.facebook.com/bhume/posts/10215793636935785
ประกาศ ประกาศ ที่นัดกันเรื่อง digital ID เย็นนี้ ห้องเล็กมากนะครับ นั่งได้ไม่เกิน 20 คน คนที่จะมาอยากขอให้เป็นคนที่สนใจจะมา contribute จริงๆ ยังไม่ทราบรายละเอียดไม่เป็นไร มาแล้วก็จะมีคนเล่าให้ฟัง แต่อยากได้เฉพาะคนที่อยากช่วยลงมือลงแรง นอกเวลางาน เสาร์อาทิตย์ fulltime parttime ได้หมด แต่ถ้าแค่อยากมานั่งฟัง กลัวตกรถไฟ รบกวนรอโอกาสหน้านะครับ ห้องขนาดจำกัด นัดวันนี้ไม่ได้นัดเล่าให้ฟัง นัดคุยหารือแนวทางการทำงาน ลงมือสร้างจริงๆ

**Comment by dtinth** [comment]
Thanks!
