### ISSUE TITLE
[Event] TDD Node.js by Pongneng and JJ

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#112]
### Date and time
2018-04-01
09:00 ~ 17:00

### Location
GeekyBase
https://goo.gl/maps/gDHKjgcXF7G2

### Links
- Facebook event: https://web.facebook.com/events/125199521652607/

### Event summary
Hand-on experience (and pain and may be some sobbing) about TDD Node.js from developer to developer.

### Event description

**Comment by dtinth** [comment]
Many thanks!
