### ISSUE TITLE
[Event] Vue, Basic View

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#113]
### Date and time
2018-04-07
09:00 ~ 16:00

### Location
Geeky Base: https://goo.gl/maps/YMBYYLJdRck

### Links
- Facebook event: https://www.facebook.com/events/1030472940434585/

### Event summary
intro to Vue.js, Basic Vue, **คอร์สทดลองสอน**

### Event description

intro to Vue.js

- Why Vue?
- Comparison with React, Angular

Basic Vue

- Vue structure
- Syntax
- Life cycle
- vue-router, vuex
- mini project
**คอร์สทดลองสอน**

**Comment by dtinth** [comment]
Thanks, but it seems the facebook event is not working yet...

![image](https://user-images.githubusercontent.com/193136/38171981-040b01b6-35ce-11e8-93e1-374702a4b5e4.png)

I need at least one working link to add this to the DB.

Much appreciated!

**Comment by PH9** [comment]
Sorry for that 

I decided to close this issue sice instructor want to be internal pilot course
