### ISSUE TITLE
[Event] Blockchain Technology for Developer

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#114]
### Date and time
2018-05-03 ~ 2018-05-04
09:00 ~ 16:00

2018-08-09 ~ 2018-08-10
09:00 ~ 16:00

2018-12-03 ~ 2018-12-04
09:00 ~ 16:00

### Location
https://goo.gl/maps/A4nfM8cKv4Q2

### Links
- Tickets: www.imcinstitute.com/training/course-registration
- Eirly bird 8,900 exclude vat.

- Facebook event: https://www.facebook.com/events/2081082005482165/

### Event summary
Blockchain เป็นเทคโนโลยีที่ได้รับการกล่าวถึงกันอย่างมากมาย เพราะเป็นการเปลี่ยนแปลงแนวคิดครั้งใหญ่ไม่เฉพาะแวดวงทางการเงินเท่านั้น แต่ยังเป็นการพลิกแนวคิดของวงการคอมพิวเตอร์และธุรกิจอีกด้วย

### Event description
มีการคาดการณ์จากผู้รู้และนักคิดหลายท่านว่า Blockchain จะเป็นตัวพลิกโฉมหน้าโลกในอนาคตอย่างที่ไม่เคยมีผู้ใดนึกถึงมาก่อน อีกทั้งยังทำให้คนตั้งคำถามถึงหน่วยงานกลางทั้งหลายรวมทั้งอำนาจรัฐด้วยว่ามีความจำเป็นเพียงใด ดังนั้นทุกคนควรหันมาทำความเข้าใจในเรื่องนี้อย่างจริงจังและนำไปคิดว่าจะเกิดผลกระทบจาก Blockchain กับตัวเราและองค์กรของเราอย่างไร
Course นี้นอกจากจะปูพื้นฐานความเข้าใจเกี่ยวกับ Blockchain และการนำไปประยุกต์ใช้งานแล้ว ยังพาท่านสัมผัสกับการสร้างและเขียนโปรแกรมบน Blockchain อีกด้วย เพื่อให้เห็นว่าเราสามารถนำไปประยุกต์ใช้ได้ง่ายดายเพียงใด

https://docs.google.com/document/d/1X7qt-mrJZjZ-y78FRmzR02kRsHKTyO0Dta80SohwGAc/edit

**Comment by dtinth** [comment]
Hello, thanks for submitting the event, but per [our event criteria](https://github.com/ThaiProgrammer/tech-events-calendar/blob/master/CONTRIBUTING.md#criteria-for-events), paid workshops of commercial nature are not allowed.

**Comment by PH9** [comment]
Ok, At first I tought it was free.
But after read description found it not free.
So I updated this issue.

To align with criteria. I decided to close this issue.

Thanks
