### ISSUE TITLE
[Event] เขียน Swift กันค่ะ

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#115]
### Date and time
2018-05-10
09:00 ~ 17:30

### Location
GeekyBase https://goo.gl/maps/zEh5hJ3A6P72

### Link
- Facebook event: https://web.facebook.com/events/185373065603790/

### Event summary
บัตรจับมือขายทำไม มีแต่บัตรเขียนโค้ดค่ะ

**Comment by dtinth** [comment]
Thanks krub!
