### ISSUE TITLE
HomePage.vue:42-45: Replace this image list with an...

### ISSUE THREAD

**Issue by 0pdd** [ThaiProgrammer/tech-events-calendar#118]
The puzzle `101-4b14d300` from #101 has to be resolved:

https://github.com/ThaiProgrammer/tech-events-calendar/blob/c0ae3611c3b8d10654dc3460fd4615014434e6b7/website/src/components/HomePage.vue#L42-L45

The puzzle was created by Thai Pangsakulyanont on 06-Apr-18. 

Estimate: 0 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
