### ISSUE TITLE
[Event] «iOSDevTH Meetup #12»

### ISSUE THREAD

**Issue by macbaszii** [ThaiProgrammer/tech-events-calendar#123]
### Date and time
2018-06-26
18:00 ~ 21:00

### Location
Skooldio https://goo.gl/maps/f3MNyeaAdx32

### Links
- Website: https://www.facebook.com/groups/iosthailand/
- Tickets: https://www.eventpop.me/e/3712-iosdevth-12

### Event summary
Area for meet up with iOS Developers in Bangkok (also Thailand)

### Event description

Topics
1. A brief summary of WWDC 2018 - Pitiphong, Omise
Let's see what's new in the WWDC 2018 especially on the iOS platform. We'll walkthrough on many things announced in the WWDC 2018. Let's see what we can do in the iOS 12.

2. Writing High-Performance Swift Code - Thongchai, Rakuten Viki
Thongchai (Hlung) will be sharing about dimensions of performance for Swift language, starting from the basics of  allocation, reference counting, and method dispatch. Then he will share stories and ways the compiler can optimize our code and how we can take advantage of it. Finally, he will use Hopper disassembler to inspect how the compiler modifies our code.

**Comment by dtinth** [comment]
Thanks!!

**Comment by dtinth** [comment]
@macbaszii Hey sorry I was very busy. I have added your event in c2f01ba53264c21ea03a8865c9ef72fc3d8a6081 and it will be added to the calendar under “past events.”

We are looking for more collaborators who can help with keeping this project up-to-date with new events. Interested?
