### ISSUE TITLE
Are there any alternative software projects similar to tech-events-calendar?

### ISSUE THREAD

**Issue by eriksjolund** [ThaiProgrammer/tech-events-calendar#143]
I hope I've understood the software design of tech-events-calendar correctly:

The tech-events-calendar stores the information for each event in a separate text file.
GitHub pull requests is the way for external people to submit new events to the calendar.
Scripts in tech-events-calendar then generate a web site and google calendar events.

I really like this software design.
Is there any other software projects similar to tech-events-calendar?

Especially I am looking for open source software.
It looks like tech-events-calendar is not open source software because I can't find
any license. I also saw a GitHub issue where the missing software license was discussed.
https://github.com/ThaiProgrammer/tech-events-calendar/issues/100

**Comment by dtinth** [comment]
Please feel free to use the code from this project — I won’t sue you. :) As per the discussion in #100, the code uses an MIT license.

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
