### ISSUE TITLE
Event: Code in the Dark Thailand #1: BKK 2018

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#145]
Name: Code in the Dark Thailand #1: BKK 2018
Date: 10 October 2018
Time: 19:00 - 22:00
Ticket URL: https://www.eventpop.me/e/4303-code-in-the-dark-thailand
Fan page: https://www.facebook.com/codecraftbkk/

Organizer: The Stupid Hackathon Thailand
Organizer Face Page: https://www.facebook.com/StupidHackTH/

Location: cøde CRAFT Bar & Studio, Pracha Rat Sai 2 Road, Bang Sue, Bangkok, Thailand 
Location URL: https://goo.gl/maps/pqg22tJiBsD2
Location Fan Page: https://www.facebook.com/pg/codecraftbkk

**Comment by PH9** [comment]
not merge yet

**Comment by PH9** [comment]
Not merge yet

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
