### ISSUE TITLE
[Feature Request] tell us how many character we use if it over sizing

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#159]
Now it only tell the maximum

**Comment by dtinth** [comment]
Great idea!

Please note that our Editor page tells you how many characters you used.
I recommend testing the data file in the Editor.
https://calendar.thaiprogrammer.org/editor

But maybe good to have it in linting outputs as well!

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
