### ISSUE TITLE
Add support for "Co-creation Camp" category

### ISSUE THREAD

**Issue by dtinth** [ThaiProgrammer/tech-events-calendar#163]
Right now, I cannot merge #142 due to parser not supporting “Co-creation Camp” category.

Why a new category? To distinguish “Startup weekend”-style events (which focuses on ideas and pitching) from actual “Hackathon” (which focuses on technical stuff).

If you can think of a better category name, please feel free to make a suggestion!

**Comment by chonla** [comment]
https://github.com/ThaiProgrammer/tech-events-calendar/pull/164. @dtinth

**Comment by dtinth** [comment]
Closed via #164.

**Comment by dtinth** [comment]
Thanks!
