### ISSUE TITLE
Could not access editor

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#172]
https://calendar.thaiprogrammer.org/editor

I have tried on

- `macOS Mojave 10.14.1 beta (18B45d)`
- `Safari 12.0.1`
- `Google Chrome 70.0.3538.67 (Official Build) (64-bit)`
- `Firefox 62.0.3 (64-bit)`
- `Opera developer 58.0.3111.0`
- `Google Chrome Version 72.0.3588.0 (Official Build) canary (64-bit)`

and it shown nothing

<img width="952" alt="screen shot 2561-10-22 at 15 31 31" src="https://user-images.githubusercontent.com/6365973/47283955-9eb02e80-d60f-11e8-9560-9a1c3a0c2678.png">

It may not about browser, I guess.

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
