### ISSUE TITLE
Event: Angular Meetup

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#174]
Still not announce about ticket yet

https://web.facebook.com/groups/angularjs.th/permalink/1138244476350217/

![44381610_10205177837441816_3455510547812843520_n](https://user-images.githubusercontent.com/6365973/47284282-ff8c3680-d610-11e8-83a6-f035038fbbef.jpg)

**Comment by rayriffy** [comment]
Merged #180
