### ISSUE TITLE
Question, Can we add international conference 

### ISSUE THREAD

**Issue by PH9** [ThaiProgrammer/tech-events-calendar#179]
Can we add international tech event that Thai always join
For example: IOS Conf SG, Gopher Conf SG, JS Conf Asia

Or even interesting event like Apple Special Event

**Comment by dtinth** [comment]
Yes, if Thai people or people who lives in Thailand go regularly, then sure, let's add it :) Want to encourage more developers to join international conferences.

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
