### ISSUE TITLE
TBD Event: Code in the Dark Thailand #2 : CNX 2018

### ISSUE THREAD

**Issue by Nann** [ThaiProgrammer/tech-events-calendar#181]
Name: Code in the Dark Thailand: CNX 2018
Date: 15 December 2018
Time: 19:00 - 22:00
Ticket URL: https://eventpop.me/e/...
Fan page: https://www.facebook.com/igeargeek/

Organizer: I GEAR GEEK
Organizer Face Page: https://www.facebook.com/igeargeek/

Location: THiNKNET CNX : เจ็ดยอด
Location URL: https://goo.gl/maps/wMvE8rkqQc62

**Comment by rayriffy** [comment]
Merged #182
