### ISSUE TITLE
Young Webmaster Camp ครั้งที่ 16

### ISSUE THREAD

**Issue by happyudong555** [ThaiProgrammer/tech-events-calendar#183]
**Event name:** Young Webmaster Camp 16TH
**Topic :** Ready to Disrupt นวัตกรรมเว็บเปลี่ยนโลก
**Detail** : กิจกรรมที่จะให้น้องๆ นักศึกษา มหาวิทยาลัย ทั่วประเทศไทย ที่สนใจทางด้านเว็บ ได้มาทำกิจกรรม แลกเปลี่ยนความรู้ ร่วมกันภายในกิจกรรม โดยภายในงานจะมีผู้เชี่ยวชาญทางด้านเว็บมาให้คำแนะนำต่างๆ เพื่อนำไปต่อยอดได้ในอนาคต

**สาขาที่เปิดรับสมัค**ร 

- Content
- Design
- Marketing
- Programming

Date: 22-25 December 2018
location : คณะเทคโนโลยีสารสนเทศ สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง (IT KMITL)
location URL : https://goo.gl/maps/3jiQ1qoA1XQ2

Organizer : Young Webmaster Camp
Organizer Fan Page URL: https://www.facebook.com/pg/ywcth/about/?ref=page_internal

Register URL : https://ywc16.ywc.in.th/
Ticket price : Free

for hacktoberFest issue

**Comment by rayriffy** [comment]
Merged #184
