### ISSUE TITLE
Permit cross-origin access in the JSON API

### ISSUE THREAD

**Issue by phoomparin** [ThaiProgrammer/tech-events-calendar#24]
In the JSON API (https://thaiprogrammer-tech-events-calendar.spacet.me/calendar.json), cross-origin resource sharing (CORS) seems to be disallowed. This makes it more difficult to directly consume the JSON API from static web applications.

If this is not the intended behavior, please consider enabling CORS by adding `Access-Control-Allow-Origin: *` to your API endpoint.

Thanks! 😄

**Comment by dtinth** [comment]
I am using Netlify to deploy this site (it’s so easy to setup, and Netlify helps with generating a preview deploy for each PR!).

They seem to support CORS but requires configuration:

https://www.netlify.com/docs/headers-and-basic-auth/

Can you help with this as I am having other priorities? If I understood the docs correctly, adding a config file at `public/_headers` should do it.

**Comment by dtinth** [comment]
I am on it now.

**Comment by dtinth** [comment]
CORS is implemented.

**Comment by dtinth** [comment]
Thanks for the suggestion! :D
