### ISSUE TITLE
og:image

### ISSUE THREAD

**Issue by dtinth** [ThaiProgrammer/tech-events-calendar#40]
Add og:image so that the website can be easily shared to Facebook

**Comment by mahasak** [comment]
Sound interesting ... What kind of image na @dtinth  ?

**Comment by dtinth** [comment]
This kind of image: https://www.h3xed.com/web-and-internet/how-to-use-og-image-meta-tag-facebook-reddit

Basically, it is a 1200x1200 image. When shared on some platform, it will render a square image. On facebook, the 1200x630 pixels in the middle is displayed.

This can make it easier to share the project on Facebook :D

**Comment by dtinth** [comment]
I added a simple og:image as part of #50. Therefore this can be closed.
