### ISSUE TITLE
[Project] Run Jest on CI

### ISSUE THREAD

**Issue by dtinth** [ThaiProgrammer/tech-events-calendar#58]
Status: Being worked on by @komcal 

---

Right now the CI checks whether the data is correct by running the data processing script, but did not check whether the data processing script itself works or not.

The data processing code (`lib/parseMarkdown.js`) already has tests (`lib/parseMarkdown.test.js`) using [Jest](https://facebook.github.io/jest/). I run it locally, but I didn’t make it run on CI yet.

**Tasks:**

1. Add a `"script"` called `"test"` in `package.json` to run `jest`. e.g. `yarn test` should run `jest`.

2. Configure CircleCI (`.circleci/circle.yml`) to run `yarn test` on every commit.

**Comment by komcal** [comment]
Can I work on this?

**Comment by dtinth** [comment]
Sure, please do! ^_^
