### ISSUE TITLE
Should it be `yarn dev` or `yarn website`?

### ISSUE THREAD

**Issue by suksit** [ThaiProgrammer/tech-events-calendar#66]
`README.md` says

> สั่ง `yarn website` เพื่อเปิดเซิฟเวอร์สำหรับพัฒนาเว็บไซต์ โดยสามารถดูเว็บไซต์ได้ที่ http://localhost:8080

But according to `package.json`, you have to run `yarn dev` to start the dev server.

So which file should we update -- `README.md` or `package.json`?

**Comment by dtinth** [comment]
Thanks for submitting an issue :)

Yep, either README.md or package.json should be updated. I am fine with
both, because I don't know what should be the appropriate script name.
