### ISSUE TITLE
`yarn build-json` creates `-p` and `tmp` directories

### ISSUE THREAD

**Issue by suksit** [ThaiProgrammer/tech-events-calendar#73]
I'm not sure whether this only happens on Windows machine... but it seems
```javascript
require('child_process').execSync('mkdir -p tmp')
```
in `scripts/generate-json.js` doesn't work as expected -- it creates `-p` directory along with `tmp` directory:

![bug](https://user-images.githubusercontent.com/115629/36731784-56730d5c-1bfe-11e8-8640-9ccb29095c9b.png)

And if I run the command again, this time it will produce errors:

![bug-2](https://user-images.githubusercontent.com/115629/36732360-1c07cd86-1c00-11e8-8c20-5f053adb90bd.png)

I tested using both Git Bash and Command Prompt and the results were consistent. I can create a PR to fix this but wanna make sure that it's not just me or my setup 😑

**Comment by dtinth** [comment]
Oops, I haven’t tested it on Windows at all. Good catch!

I think, the most fix is to use `require('mkdirp').sync('tmp')`. :)
