### ISSUE TITLE
Google Calendar not updated

### ISSUE THREAD

**Issue by suksit** [ThaiProgrammer/tech-events-calendar#84]
It seems the [Google Calendar](https://calendar.google.com/calendar/embed?src=j5i0o6v2ihfboe19upl9lhonbci6ankr%40import.calendar.google.com&ctz=Asia%2FBangkok) data is not updated when new events are added e.g. the LINE Developer Meetup doesn't show up in the calendar yet.

I'm not sure how this works -- maybe it will get updated after some scheduled scan interval?

**Comment by dtinth** [comment]
@suksit Google Calendar is periodically fetches the ICS file with an interval of roughly 1 day.

For today, it updated at 11:33 a.m.:

![image](https://user-images.githubusercontent.com/193136/36835775-e791db8a-1d69-11e8-9f7e-197fd922e346.png)

**Comment by suksit** [comment]
Ah... thanks for clarification 🤣
