### ISSUE TITLE
[Event] «Angular Developers Thailand Meetup March 2018»

### ISSUE THREAD

**Issue by perjerz3434** [ThaiProgrammer/tech-events-calendar#85]
### Date and time
2018-03-05
18:30 ~ 22:00

### Location

 LINK Collaboration Space, ถนน บรรทัดทอง แขวง รองเมือง เขต ปทุมวัน กรุงเทพมหานคร ประเทศไทย 
https://www.google.co.th/maps/place/LINK+Collaboration+Space/@13.7369995,100.5200761,17z/data=!4m5!3m4!1s0x30e299312368f6eb:0x822246345e9e0e3b!8m2!3d13.7394382!4d100.5219107

### Links

- Website: -
- Tickets: https://www.eventpop.me/e/3063-angular-meetup-march-2018
- Facebook event: https://www.facebook.com/events/188547875079146/

### Event summary

Event ​พบปะและแลกเปลี่ยนเรื่อง Angular

### Angular Developers Thailand Meetup ประจำเดือนมีนาคม

Event ​พบปะและแลกเปลี่ยนเรื่อง Angular
Session มีดังนี้ (อาจมีการปรับเปลี่ยน)
1. RouteReuseStrategy by Khun Tum 6.30 P.M. - 7.30 P.M.
2. Angular 6.0 Panel Discussion 7.30 PM - 9.00 PM
3. Networking 9.00 P.M. - 10.00 P.M.

สำหรับท่านที่สนใจจะแชร์ 2 - 10 นาที หรือ เป็นสปีกเกอร์สามารถติดต่อทีมงาน หรือใน Facebook Group ได้เลยครับ

สถานที่
LINK Collaboration Space พื้นที่ Co-Working และสร้างสรรค์ไอเดีย บนถนนบรรทัดทอง

วิธีการเดินทางมา LINK Collaboration Space 
1. มาด้วย MRT ขึ้นสถานีหัวลำโพง แล้วเดินไปก็ได้ 10 นาที หรือต่อแท๊กซี่ 
2. มาด้วย BTS ลงสถานีสนามกีฬาแห่งชาติทางออก 2 แล้วเดินไปก็ได้ 10 นาที หรือต่อแท๊กซี่
แผนที่: https://goo.gl/maps/wtZZAo89Rft

แล้วเจอกันครับ

**Comment by dtinth** [comment]
Thanks for the information!
