### ISSUE TITLE
Event page is not SNS friendly

### ISSUE THREAD

**Issue by kindraywind** [ThaiProgrammer/tech-events-calendar#87]
I noticed this one when I was trying to implement sharing feature on my [iOS app](https://github.com/kindraywind/ThaiTechEventCalendar-iOS).
When I tried to share an interesting event, the post wasn't look informative. (see the pic below)
![img_fff001f59275-1](https://user-images.githubusercontent.com/500289/36855874-fd30644a-1db7-11e8-9c77-3387551b8264.jpeg)

I suspect the [og markup](https://developers.facebook.com/docs/sharing/webmasters) here isn't dynamically changed regarding an event information.
<img width="934" alt="screen shot 2018-03-02 at 01 18 26" src="https://user-images.githubusercontent.com/500289/36855982-3c1d7f6c-1db8-11e8-8682-577787c2ee8d.png">

**Comment by dtinth** [comment]
Thanks for reporting an issue.

Since this is a single-page application, every page looks the same (a bit unfortunate).

However, there is a simple workaround: Generate HTML files for each event. We can do this easily by copying `index.html` file for each event, and modifying the `<meta>` tags.

**Comment by dtinth** [comment]
I’m going to solve this live on Facebook tomorrow :D

**Comment by dtinth** [comment]
https://www.facebook.com/dtinth/videos/10209620169735240/
