### ISSUE TITLE
We need a logo. [Graphic designers, please help!]

### ISSUE THREAD

**Issue by dtinth** [ThaiProgrammer/tech-events-calendar#90]
To make [this site](https://calendar.thaiprogrammer.org/) a Progressive Web App (#89), first we need a logo to create the app icons. App icon size should be at least 192x192.

Please comment with the logo image (you can attach images by dragging the image into the comment box). If possible, please also link to source file (e.g. photoshop/sketch). Thanks~

**Comment by hern12** [comment]
![calendar-1](https://user-images.githubusercontent.com/13413078/37038536-ab5ece94-2187-11e8-8561-7ee070050f69.gif)
![calendar-2](https://user-images.githubusercontent.com/13413078/37038537-ab918adc-2187-11e8-803f-4afb24988fb4.gif)

คิดอะไรไม่ออกแต่อยากช่วยด้วยครับเพิ่งมาติดตามจากไลฟ์สดชอบมากครับอยากจะถามคำถามเหมือนกันแต่ถามไม่ได้มันไม่มีช่องคอมเม้นครับท่าน (ผมไม่ใช่ Designer รูปกะโหลกกะลาหน่อยนะครับ sorry)

**Comment by kindraywind** [comment]
ทำสรุป design guideline(theme, color scheme, font) จาก #47 ก่อน แล้วมาปรับใช้กับ logo ไหมครับ

**Comment by dtinth** [comment]
Closing the issue as this project is being deprecated.
